### ISSUE TITLE
[FEATURE]: Implement Dashboard Endpoint

### ISSUE THREAD

**Issue by ttebify** [ttebify/anonymous-comrades#10]
## Task Description:

This issue aims to create the necessary endpoint to retrieve dashboard information. The endpoint will provide various details, including the current user's profile, total message count, total room count, and public chats with counts. The specific endpoint to be implemented is as follows:

## Dashboard Endpoint:

- GET /api/dashboard: Retrieve dashboard information

Example Response:
```json
{
  "userProfile": {
    "name": "John Doe",
    "email": "john.doe@example.com",
    "avatar": "https://example.com/avatar.png"
  },
  "messageCount": 150,
  "chatRoomCount": 10,
  "publicChats": [
    {
      "id": "01EJCJKH0ZJFJS7CJ15KHF6MYD",
      "content": "This is a public chat message.",
      "hidden": false,
      "created_by": "01EJCJKH0ZJFJS7CJ15KHF6MYD",
      "created_at": "2023-07-04T10:30:00Z",
      "updated_at": "2023-07-04T10:30:00Z"
    },
    {
      "id": "01EJCJKH0ZJFJS7CJ15KHF6MYE",
      "content": "Another public chat message.",
      "hidden": false,
      "created_by": "01EJCJKH0ZJFJS7CJ15KHF6MYE",
      "created_at": "2023-07-04T11:15:00Z",
      "updated_at": "2023-07-04T11:15:00Z"
    },
  ]
}
```

## Acceptance Criteria:

- [x] The GET endpoint should successfully retrieve dashboard information.
- [ ] The response should include the current user's profile, total message count, total room count, and public chats with counts.
- [ ] The endpoint should be correctly implemented and integrated into the project.
- [ ] An example response in JSON format should be provided.

## Implementation Guidelines:

1. Create the API route and corresponding controller method for the dashboard endpoint.
2. Implement the logic to gather the required information, such as the current user's profile, total message count, total room count, and public chats with counts.
3. Test the endpoint locally to ensure the correct retrieval of dashboard information.
4. Update the API documentation, if necessary, to include details about the dashboard endpoint and the example response.
